version: 2
updates:
  - package-ecosystem: "poetry" # <--- Aquí estaba el cambio clave
    directory: "/"
    schedule:
      interval: "weekly"
    # Opcional: Para agrupar todas las actualizaciones en una sola PR y no saturar
    groups:
      all-dependencies:
        patterns: ["*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
